### ISSUE TITLE
Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by char518** [Wujiaxuan007/trantor-plugin-error-receiver#23]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.NullPointerException
	at io.terminus.trantor.plugin.utils.TrantorUtils.getRootNode(TrantorUtils.java:100)
	at io.terminus.trantor.plugin.navigator.action.search.TrantorSearchContributor.buildResources(TrantorSearchContributor.java:65)
	at io.terminus.trantor.plugin.navigator.action.search.TrantorSearchContributor.<init>(TrantorSearchContributor.java:40)
	at io.terminus.trantor.plugin.navigator.action.search.TrantorSearchContributor$Factory.createContributor(TrantorSearchContributor.java:141)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereManagerImpl.createContributors(SearchEverywhereManagerImpl.java:182)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereManagerImpl.show(SearchEverywhereManagerImpl.java:81)
	at com.intellij.ide.actions.SearchEverywhereBaseAction.showInSearchEverywherePopup(SearchEverywhereBaseAction.java:62)
	at com.intellij.ide.actions.SearchEverywhereAction.actionPerformed(SearchEverywhereAction.java:102)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:239)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:260)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:239)
	at com.intellij.openapi.keymap.impl.ModifierKeyDoubleClickHandler$MyDispatcher.run(ModifierKeyDoubleClickHandler.java:265)
	at com.intellij.openapi.keymap.impl.ModifierKeyDoubleClickHandler$MyDispatcher.handleModifier(ModifierKeyDoubleClickHandler.java:230)
	at com.intellij.openapi.keymap.impl.ModifierKeyDoubleClickHandler$MyDispatcher.dispatch(ModifierKeyDoubleClickHandler.java:167)
	at com.intellij.openapi.keymap.impl.ModifierKeyDoubleClickHandler.lambda$new$0(ModifierKeyDoubleClickHandler.java:84)
	at com.intellij.ide.IdeEventQueue.dispatchByCustomDispatchers(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:735)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Version and Environment Details
Operation system: macOS 12.2.1
IDE version: IU-213.7172.25
Plugin version: 0.6.0

**Comment by Wujiaxuan007** [comment]
0.6.1 已修复
