### ISSUE TITLE
Exception: java.lang.IllegalStateException: @NotNull method io/terminus/trantor/plugin/meta/AbstractModuleResource$1.getPresentableText must not return null

### ISSUE THREAD

**Issue by 22GNUs** [Wujiaxuan007/trantor-plugin-error-receiver#24]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.IllegalStateException: @NotNull method io/terminus/trantor/plugin/meta/AbstractModuleResource$1.getPresentableText must not return null
	at io.terminus.trantor.plugin.meta.AbstractModuleResource$1.$$$reportNull$$$0(AbstractModuleResource.java)
	at io.terminus.trantor.plugin.meta.AbstractModuleResource$1.getPresentableText(AbstractModuleResource.java:27)
	at com.intellij.ide.util.gotoByName.GotoFileCellRenderer.doCustomizeNonPsiElementLeftRenderer(GotoFileCellRenderer.java:115)
	at com.intellij.ide.actions.SearchEverywherePsiRenderer.customizeNonPsiElementLeftRenderer(SearchEverywherePsiRenderer.java:168)
	at com.intellij.ide.util.PsiElementListCellRenderer$LeftRenderer.customizeCellRenderer(PsiElementListCellRenderer.java:157)
	at com.intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:47)
	at com.intellij.ide.util.PsiElementListCellRenderer.getListCellRendererComponent(PsiElementListCellRenderer.java:246)
	at com.intellij.ide.actions.searcheverywhere.MixedListFactory$1.getListCellRendererComponent(MixedListFactory.java:81)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:197)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.locationToIndex(BasicListUI.java:1004)
	at java.desktop/javax.swing.JList.locationToIndex(JList.java:1600)
	at java.desktop/javax.swing.JList.getLastVisibleIndex(JList.java:1080)
	at com.intellij.ui.ScrollingUtil.getVisibleRowCount(ScrollingUtil.java:226)
	at com.intellij.ui.ScrollingUtil.visibleRowCount(ScrollingUtil.java:385)
	at com.intellij.ui.ScrollingUtil._ensureIndexIsVisible(ScrollingUtil.java:161)
	at com.intellij.ui.ScrollingUtil._move(ScrollingUtil.java:488)
	at com.intellij.ui.ScrollingUtil._moveDown(ScrollingUtil.java:474)
	at com.intellij.ui.ScrollingUtil.moveDown(ScrollingUtil.java:234)
	at com.intellij.ui.ScrollingUtil$ListMoveDownAction.actionPerformed(ScrollingUtil.java:765)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:572)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:702)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:265)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:698)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:641)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:583)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:466)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:455)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:223)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Version and Environment Details
Operation system: macOS 12.0.1
IDE version: IU-213.5744.223
Plugin version: 0.6.0
Trantor version: 1.0

**Comment by Wujiaxuan007** [comment]
0.6.2 已修复 : )
