### ISSUE TITLE
Exception: java.lang.Throwable: Assertion failed: Directory index can only be queried after project initialization

### ISSUE THREAD

**Issue by goooodle** [Wujiaxuan007/trantor-plugin-error-receiver#29]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.Throwable: Assertion failed: Directory index can only be queried after project initialization
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:69)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:172)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getDirectoriesByPackageName(DirectoryIndexImpl.java:131)
	at com.intellij.openapi.module.ResourceFileUtil.findResourceFileInScope(ResourceFileUtil.java:35)
	at io.terminus.trantor.plugin.utils.TrantorUtils.lambda$isTrantorProject$0(TrantorUtils.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:907)
	at io.terminus.trantor.plugin.utils.TrantorUtils.isTrantorProject(TrantorUtils.java:86)
	at io.terminus.trantor.plugin.navigator.TreeWindow.shouldBeAvailable(TreeWindow.java:33)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:262)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:248)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$beanToTask(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt:278)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.computeToolWindowBeans(ToolWindowSetInitializer.kt:274)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:101)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:83)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

### Version and Environment Details
Operation system: macOS 12.3
IDE version: IU-221.5080.210
Plugin version: 0.6.2

**Comment by Wujiaxuan007** [comment]
😄 已兼容最新版 IDEA 2022.1，请升级至 0.6.4+，
