### ISSUE TITLE
Exception: com.intellij.diagnostic.PluginException: Cannot create class io.terminus.trantor.plugin.project.manager.TProjectManager (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Trantor, id=io.terminus.trantor.plugin, descriptorPath=plugin.xml, path=~\AppData\Roaming\Google\AndroidStudio2021.1\plugins\Trantor-Plugin, version=0.6.5, package=null), packagePrefix=null, instanceId=57, state=active))

### ISSUE THREAD

**Issue by PusakaOfJavaHack** [Wujiaxuan007/trantor-plugin-error-receiver#31]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
com.intellij.diagnostic.PluginException: Cannot create class io.terminus.trantor.plugin.project.manager.TProjectManager (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Trantor, id=io.terminus.trantor.plugin, descriptorPath=plugin.xml, path=~\AppData\Roaming\Google\AndroidStudio2021.1\plugins\Trantor-Plugin, version=0.6.5, package=null), packagePrefix=null, instanceId=57, state=active))
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:297)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:81)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:760)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:699)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:592)
	at com.intellij.serviceContainer.ComponentManagerImpl.getLightService$intellij_platform_serviceContainer(ComponentManagerImpl.kt:566)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:478)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
	at io.terminus.trantor.plugin.navigator.TTreeStructure.<init>(TTreeStructure.java:75)
	at io.terminus.trantor.plugin.navigator.TrantorNavigator.initToolWindow(TrantorNavigator.java:52)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:325)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:742)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/idea/maven/project/MavenProjectsManager
	at io.terminus.trantor.plugin.project.manager.TProjectManager.<init>(TProjectManager.java:50)
	... 41 more
```

### Version and Environment Details
Operation system: Windows 10 10.0
IDE version: AI-211.7628.21.2111.8309675
Plugin version: 0.6.5

**Comment by Wujiaxuan007** [comment]
idea 有装 maven 插件吗？

**Comment by Wujiaxuan007** [comment]
windows 环境，IDEA 有装 Maven 插件吗？

Caused by: java.lang.NoClassDefFoundError: org/jetbrains/idea/maven/project/MavenProjectsManager

**Comment by Wujiaxuan007** [comment]
> ### Description
> ### Stacktrace
> Please paste the full stacktrace from the IDEA error popup.
> 
> ```
> com.intellij.diagnostic.PluginException: Cannot create class io.terminus.trantor.plugin.project.manager.TProjectManager (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Trantor, id=io.terminus.trantor.plugin, descriptorPath=plugin.xml, path=~\AppData\Roaming\Google\AndroidStudio2021.1\plugins\Trantor-Plugin, version=0.6.5, package=null), packagePrefix=null, instanceId=57, state=active))
> 	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:297)
> 	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
> 	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:81)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:760)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:699)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:592)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.getLightService$intellij_platform_serviceContainer(ComponentManagerImpl.kt:566)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:478)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
> 	at io.terminus.trantor.plugin.navigator.TTreeStructure.<init>(TTreeStructure.java:75)
> 	at io.terminus.trantor.plugin.navigator.TrantorNavigator.initToolWindow(TrantorNavigator.java:52)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
> 	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:325)
> 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
> 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
> 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
> 	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:742)
> 	... 36 more
> Caused by: java.lang.NoClassDefFoundError: org/jetbrains/idea/maven/project/MavenProjectsManager
> 	at io.terminus.trantor.plugin.project.manager.TProjectManager.<init>(TProjectManager.java:50)
> 	... 41 more
> ```
> 
> ### Version and Environment Details
> Operation system: Windows 10 10.0 IDE version: AI-211.7628.21.2111.8309675 Plugin version: 0.6.5

1
