### ISSUE TITLE
Exception: java.lang.ClassNotFoundException: com.intellij.util.SlowOperations PluginClassLoader[PluginDescriptor(name=Trantor, id=io.terminus.trantor.plugin, path=/Users/terminus/Library/Application Support/JetBrains/IdeaIC2020.3/plugins/Trantor-Plugin, version=0.6.5)] com.intellij.ide.plugins.cl.PluginClassLoader@7305d287

### ISSUE THREAD

**Issue by bulbuls** [Wujiaxuan007/trantor-plugin-error-receiver#34]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.ClassNotFoundException: com.intellij.util.SlowOperations PluginClassLoader[PluginDescriptor(name=Trantor, id=io.terminus.trantor.plugin, path=/Users/terminus/Library/Application Support/JetBrains/IdeaIC2020.3/plugins/Trantor-Plugin, version=0.6.5)] com.intellij.ide.plugins.cl.PluginClassLoader@7305d287
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at io.terminus.trantor.plugin.utils.InvokeUtils.allowSlowOperations(InvokeUtils.java:80)
	at io.terminus.trantor.plugin.issue.lint.DeclarationImplementLint.checkImpl(DeclarationImplementLint.java:41)
	at io.terminus.trantor.plugin.issue.lint.FuncLint.getLiveIssue(FuncLint.java:29)
	at io.terminus.trantor.plugin.issue.IssueManager.lambda$getForFile$0(IssueManager.java:71)
	at com.intellij.openapi.project.DumbService.tryRunReadActionInSmartMode(DumbService.java:110)
	at io.terminus.trantor.plugin.issue.IssueManager.getForFile(IssueManager.java:53)
	at io.terminus.trantor.plugin.issue.IssueManager.getForFile(IssueManager.java:43)
	at io.terminus.trantor.plugin.issue.annotator.TrantorAnnotator.annotate(TrantorAnnotator.java:44)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:275)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$1(HighlightVisitorImpl.java:211)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:370)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:210)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Version and Environment Details
Operation system: macOS 10.16
IDE version: IC-203.8084.24
Plugin version: 0.6.5
Trantor version: 1.0

**Comment by Wujiaxuan007** [comment]
🤗 将于0.6.6修复，预计今天发版
