### ISSUE TITLE
Exception: java.lang.Exception

### ISSUE THREAD

**Issue by 22GNUs** [Wujiaxuan007/trantor-plugin-error-receiver#35]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:157)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:67)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:65)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:193)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:141)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:215)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:128)
	at com.intellij.psi.impl.source.tree.java.PsiNameValuePairImpl.getNode(PsiNameValuePairImpl.java:44)
	at com.intellij.psi.impl.source.tree.java.PsiNameValuePairImpl.getValue(PsiNameValuePairImpl.java:82)
	at com.intellij.psi.impl.PsiImplUtil.findDeclaredAttributeValue(PsiImplUtil.java:69)
	at com.intellij.psi.impl.PsiImplUtil.findAttributeValue(PsiImplUtil.java:74)
	at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.findAttributeValue(PsiAnnotationImpl.java:46)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.newEntityModel(ModelResourceLoader.java:145)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.applyModelResource(ModelResourceLoader.java:122)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.lambda$putTrantorModels$1(ModelResourceLoader.java:94)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.putTrantorModels(ModelResourceLoader.java:87)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.lambda$getData$0(ModelResourceLoader.java:80)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.getData(ModelResourceLoader.java:77)
	at io.terminus.trantor.plugin.meta.module.PluginModuleResource.loadModuleResources(PluginModuleResource.java:39)
	at io.terminus.trantor.plugin.meta.module.PluginModuleResource.getInstance(PluginModuleResource.java:25)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.concurrent.ConcurrentSkipListMap$ValueSpliterator.forEachRemaining(ConcurrentSkipListMap.java:3246)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.terminus.trantor.plugin.project.manager.TProjectManager.exploreTModules(TProjectManager.java:73)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:113)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:113)
	at io.terminus.trantor.plugin.project.manager.TProjectManager.reloadTModuleList(TProjectManager.java:67)
	at io.terminus.trantor.plugin.navigator.TTreeStructure$1.run(TTreeStructure.java:101)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

### Version and Environment Details
Operation system: macOS 12.0.1
IDE version: IU-221.5591.52
Plugin version: 0.6.6
Trantor version: 1.0

**Comment by Wujiaxuan007** [comment]
这个大概率是 idea 的偶现 bug，若影响插件使用，尝试清除缓存重启。https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000410850-How-to-avoid-Outdated-stub-in-index-error-。
