### ISSUE TITLE
Exception: java.lang.ClassCastException: class io.terminus.trantor.plugin.navigator.node.TViewActionNode cannot be cast to class io.terminus.trantor.plugin.navigator.node.TViewNode (io.terminus.trantor.plugin.navigator.node.TViewActionNode and io.terminus.trantor.plugin.navigator.node.TViewNode are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @56e2a60c)

### ISSUE THREAD

**Issue by gao001126** [Wujiaxuan007/trantor-plugin-error-receiver#37]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.ClassCastException: class io.terminus.trantor.plugin.navigator.node.TViewActionNode cannot be cast to class io.terminus.trantor.plugin.navigator.node.TViewNode (io.terminus.trantor.plugin.navigator.node.TViewActionNode and io.terminus.trantor.plugin.navigator.node.TViewNode are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @56e2a60c)
	at io.terminus.trantor.plugin.reference.ref.TViewJsonRef.resolve(TViewJsonRef.java:26)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:177)
	at com.intellij.codeInsight.TargetElementUtilBase.doGetReferenceOrReferencedElement(TargetElementUtilBase.java:165)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:204)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:248)
	at com.intellij.codeInsight.TargetElementUtilBase.doFindTargetElement(TargetElementUtilBase.java:227)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:292)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:147)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:174)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:135)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:40)
	at com.intellij.codeInsight.navigation.impl.GttdKt.gotoTypeDeclarationInner(gttd.kt:49)
	at com.intellij.codeInsight.navigation.impl.GttdKt.access$gotoTypeDeclarationInner(gttd.kt:1)
	at com.intellij.codeInsight.navigation.impl.GttdKt$gotoTypeDeclaration$1.invoke(gttd.kt:29)
	at com.intellij.codeInsight.navigation.impl.GttdKt$gotoTypeDeclaration$1.invoke(gttd.kt)
	at com.intellij.codeInsight.navigation.impl.CommonKt.processInjectionThenHost(common.kt:15)
	at com.intellij.codeInsight.navigation.impl.GttdKt.gotoTypeDeclaration(gttd.kt:29)
	at com.intellij.codeInsight.navigation.actions.GotoTypeDeclarationHandler2.getCtrlMouseInfo(GotoTypeDeclarationHandler2.kt:66)
	at com.intellij.codeInsight.navigation.actions.GotoTypeDeclarationAction.getCtrlMouseInfo(GotoTypeDeclarationAction.java:161)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.doExecute(CtrlMouseHandler.java:392)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.lambda$execute$0(CtrlMouseHandler.java:370)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Version and Environment Details
Operation system: macOS 11.6
IDE version: IU-212.5284.40
Plugin version: 0.5.1
Trantor version: 0.17

**Comment by Wujiaxuan007** [comment]
📌 请升级插件 > 0.6.6
