### ISSUE TITLE
Exception: com.intellij.diagnostic.PluginException: The default implementation of method 'getFile' is deprecated, you need to override it in 'class io.terminus.trantor.plugin.navigator.TrantorYmlFormEditor'. A proper @NotNull implementation required [Plugin: io.terminus.trantor.plugin]

### ISSUE THREAD

**Issue by Wujiaxuan007** [Wujiaxuan007/trantor-plugin-error-receiver#4]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
com.intellij.diagnostic.PluginException: The default implementation of method 'getFile' is deprecated, you need to override it in 'class io.terminus.trantor.plugin.navigator.TrantorYmlFormEditor'. A proper @NotNull implementation required [Plugin: io.terminus.trantor.plugin]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:270)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.reportDeprecatedDefault(PluginException.java:110)
	at com.intellij.openapi.fileEditor.FileEditor.getFile(FileEditor.java:127)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.updateHighlighting(ScriptClassRootsUpdater.kt:249)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.doUpdate(ScriptClassRootsUpdater.kt:197)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.doUpdate$default(ScriptClassRootsUpdater.kt:175)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater$ensureUpdateScheduled$$inlined$withLock$kotlin_core$lambda$1.run(ScriptClassRootsUpdater.kt:162)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$execute$8(BackgroundTaskUtil.java:206)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Version and Environment Details
Operation system: macOS 10.15.7
IDE version: IC-213.5744.223
Plugin version: 0.4.9

**Comment by Wujiaxuan007** [comment]
该问题将于0.4.10修复
