### ISSUE TITLE
Exception: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'baseClass' of com/intellij/psi/impl/source/PsiClassImpl.isInheritor must not be null

### ISSUE THREAD

**Issue by Terry20161226** [Wujiaxuan007/trantor-plugin-error-receiver#41]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'baseClass' of com/intellij/psi/impl/source/PsiClassImpl.isInheritor must not be null
	at com.intellij.psi.impl.source.PsiClassImpl.$$$reportNull$$$0(PsiClassImpl.java)
	at com.intellij.psi.impl.source.PsiClassImpl.isInheritor(PsiClassImpl.java)
	at io.terminus.trantor.plugin.loader.SystemFieldsProvider.getFields(SystemFieldsProvider.java:47)
	at io.terminus.trantor.plugin.loader.ModelFieldLoader.getData(ModelFieldLoader.java:79)
	at io.terminus.trantor.plugin.meta.model.PluginModelResource.loadModelResources(PluginModelResource.java:73)
	at io.terminus.trantor.plugin.meta.model.PluginModelResource.getInstance(PluginModelResource.java:38)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.applyModelResource(ModelResourceLoader.java:130)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.lambda$putTrantorModels$1(ModelResourceLoader.java:94)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.putTrantorModels(ModelResourceLoader.java:87)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.lambda$getData$0(ModelResourceLoader.java:80)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.getData(ModelResourceLoader.java:77)
	at io.terminus.trantor.plugin.meta.module.PluginModuleResource.loadModuleResources(PluginModuleResource.java:39)
	at io.terminus.trantor.plugin.meta.module.PluginModuleResource.getInstance(PluginModuleResource.java:25)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.concurrent.ConcurrentSkipListMap$ValueSpliterator.forEachRemaining(ConcurrentSkipListMap.java:3249)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.terminus.trantor.plugin.project.manager.TProjectManager.exploreTModules(TProjectManager.java:73)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:113)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:113)
	at io.terminus.trantor.plugin.project.manager.TProjectManager.reloadTModuleList(TProjectManager.java:67)
	at io.terminus.trantor.plugin.navigator.TTreeStructure$1.run(TTreeStructure.java:102)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Version and Environment Details
Operation system: macOS 12.2.1
IDE version: IU-222.3345.118
Plugin version: 0.6.7
Trantor version: 0.14

**Comment by Wujiaxuan007** [comment]
0.7.0 已修复
