### ISSUE TITLE
Exception: com.intellij.diagnostic.PluginException: 1361 ms to call on EDT RefreshTrantorApiJarAction#update@ContextToolbar (io.terminus.trantor.plugin.navigator.custom.component.toolbar.RefreshTrantorApiJarAction). Revise AnAction.getActionUpdateThread property [Plugin: io.terminus.trantor.plugin]

### ISSUE THREAD

**Issue by IsZAXIE** [Wujiaxuan007/trantor-plugin-error-receiver#43]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
com.intellij.diagnostic.PluginException: 1361 ms to call on EDT RefreshTrantorApiJarAction#update@ContextToolbar (io.terminus.trantor.plugin.navigator.custom.component.toolbar.RefreshTrantorApiJarAction). Revise AnAction.getActionUpdateThread property [Plugin: io.terminus.trantor.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.java:255)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:203)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:137)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:705)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:556)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:309)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:377)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:396)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:428)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:424)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$16(ActionUpdater.java:396)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$17(ActionUpdater.java:395)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Throwable: EDT-trace-at-512-ms
		at java.base@17.0.5/jdk.internal.jimage.ImageStringsReader.unmaskedHashCode(ImageStringsReader.java:89)
		at java.base@17.0.5/jdk.internal.jimage.ImageStringsReader.hashCode(ImageStringsReader.java:79)
		at java.base@17.0.5/jdk.internal.jimage.ImageStringsReader.hashCode(ImageStringsReader.java:74)
		at java.base@17.0.5/jdk.internal.jimage.BasicImageReader.getLocationIndex(BasicImageReader.java:306)
		at java.base@17.0.5/jdk.internal.jimage.BasicImageReader.verifyLocation(BasicImageReader.java:279)
		at java.base@17.0.5/jdk.internal.jimage.ImageReader.verifyLocation(ImageReader.java:153)
		at java.base@17.0.5/jdk.internal.module.SystemModuleFinders$SystemModuleReader.containsImageLocation(SystemModuleFinders.java:448)
		at java.base@17.0.5/jdk.internal.module.SystemModuleFinders$SystemModuleReader.find(SystemModuleFinders.java:457)
		at java.base@17.0.5/jdk.internal.loader.BuiltinClassLoader$2.run(BuiltinClassLoader.java:464)
		at java.base@17.0.5/jdk.internal.loader.BuiltinClassLoader$2.run(BuiltinClassLoader.java:459)
		at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:807)
		at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:569)
		at java.base@17.0.5/jdk.internal.loader.BuiltinClassLoader.findMiscResource(BuiltinClassLoader.java:458)
		at java.base@17.0.5/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:341)
		at java.base@17.0.5/java.lang.ClassLoader.getResource(ClassLoader.java:1403)
		at java.base@17.0.5/java.lang.ClassLoader.getResource(ClassLoader.java:1398)
		at com.intellij.ide.plugins.cl.PluginClassLoader$$Lambda$724/0x0000000100787878.apply(Unknown Source)
		at com.i...
```

### Version and Environment Details
Operation system: Windows 10 10.0
IDE version: IU-223.8617.56
Plugin version: 0.6.7

**Comment by Wujiaxuan007** [comment]
0.7.0 已修复，正在审核中，预计两天，可直接 dingding 找我拿最新插件包。
![image](https://user-images.githubusercontent.com/41990342/231389725-6a241f00-feb5-4d37-8178-f474fbf09362.png)
