### ISSUE TITLE
Exception: java.lang.Throwable: Assert: must be called on EDT

### ISSUE THREAD

**Issue by xcxiaochou** [Wujiaxuan007/trantor-plugin-error-receiver#44]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:68)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.assertIsEdt$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:181)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setAvailable(ToolWindowImpl.kt:374)
	at io.terminus.trantor.plugin.utils.TrantorUtils.setTrantorWinsAvailable(TrantorUtils.java:478)
	at io.terminus.trantor.plugin.project.listener.TProjectListener.redetermineRefresh(TProjectListener.java:94)
	at io.terminus.trantor.plugin.project.listener.TProjectListener$3.toolWindowRegistered(TProjectListener.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.intellij.openapi.wm.ex.ToolWindowManagerListener.toolWindowsRegistered(ToolWindowManagerListener.java:26)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:644)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:415)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:394)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:454)
	at jdk.proxy1/jdk.proxy1.$Proxy84.toolWindowsRegistered(Unknown Source)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing(ToolWindowSetInitializer.kt:155)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing$default(ToolWindowSetInitializer.kt:152)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:138)
	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:45)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$1.invokeSuspend(ToolWindowSetInitializer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

### Version and Environment Details
Operation system: macOS 13.2.1
IDE version: IU-231.8109.175
Plugin version: 0.6.7

**Comment by Wujiaxuan007** [comment]
0.7.0 已修复，正在审核中，预计两天，可直接 dingding 找我拿最新插件包。
![image](https://user-images.githubusercontent.com/41990342/231389725-6a241f00-feb5-4d37-8178-f474fbf09362.png)
