### ISSUE TITLE
Exception: java.lang.NoClassDefFoundError: com/esotericsoftware/minlog/Log

### ISSUE THREAD

**Issue by Terry20161226** [Wujiaxuan007/trantor-plugin-error-receiver#45]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.NoClassDefFoundError: com/esotericsoftware/minlog/Log
	at io.terminus.trantor.plugin.navigator.TTreeStructure$1.run(TTreeStructure.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.esotericsoftware.minlog.Log PluginClassLoader(plugin=PluginDescriptor(name=Trantor, id=io.terminus.trantor.plugin, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2023.1/plugins/Trantor-Plugin, version=0.6.7, package=null, isBundled=false), packagePrefix=null, instanceId=252, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 21 more

```

### Version and Environment Details
Operation system: macOS 12.2.1
IDE version: IU-231.8109.175
Plugin version: 0.6.7
Trantor version: 1.0

**Comment by Wujiaxuan007** [comment]
0.7.0 已修复，正在审核中，预计两天，可直接 dingding 找我拿最新插件包。
![image](https://user-images.githubusercontent.com/41990342/231389725-6a241f00-feb5-4d37-8178-f474fbf09362.png)
