### ISSUE TITLE
Exception: java.lang.Throwable: Assert: must be called on EDT

### ISSUE THREAD

**Issue by NewHava** [Wujiaxuan007/trantor-plugin-error-receiver#48]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:68)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.assertIsEdt$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:181)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setAvailable(ToolWindowImpl.kt:374)
	at io.terminus.trantor.plugin.utils.TrantorUtils.setTrantorWinsAvailable(TrantorUtils.java:478)
	at io.terminus.trantor.plugin.project.listener.TProjectListener.redetermineRefresh(TProjectListener.java:94)
	at io.terminus.trantor.plugin.project.listener.TProjectListener$3.toolWindowRegistered(TProjectListener.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.intellij.openapi.wm.ex.ToolWindowManagerListener.toolWindowsRegistered(ToolWindowManagerListener.java:26)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:640)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:415)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:394)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:454)
	at jdk.proxy1/jdk.proxy1.$Proxy120.toolWindowsRegistered(Unknown Source)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing(ToolWindowSetInitializer.kt:155)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing$default(ToolWindowSetInitializer.kt:152)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:138)
	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:45)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$1.invokeSuspend(ToolWindowSetInitializer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.intellij.openapi.progress.CoroutinesKt$indicatorRunBlockingCancellable$1.invoke(coroutines.kt:163)
	at com.intellij.openapi.progress.CoroutinesKt$indicatorRunBlockingCancellable$1.invoke(coroutines.kt:156)
	at com.intellij.openapi.progress.CancellationKt$ensureCurrentJob$2$1.invoke(cancellation.kt:85)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CancellationKt.executeWithJobAndCompleteIt(cancellation.kt:126)
	at com.intellij.openapi.progress.CancellationKt.ensureCurrentJob$lambda$1(cancellation.kt:83)
	at com.intellij.openapi.progress.impl.CoreProgressManager.silenceGlobalIndicator(CoreProgressManager.java:964)
	at com.intellij.openapi.progress.CancellationKt.ensureCurrentJob(cancellation.kt:82)
	at com.intellij.openapi.progress.CoroutinesKt.indicatorRunBlockingCancellable(coroutines.kt:156)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:120)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:113)
	at com.intellij.openapi.vcs.checkout.PlatformProjectCheckoutListener.processCheckedOutDirectory(ProjectDirCheckoutListener.kt:40)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.checkoutCompleted(CompositeCheckoutListener.java:71)
	at git4idea.checkout.GitCheckoutProvider$1.run(GitCheckoutProvider.java:119)
	at com.intellij.openapi.wm.impl.welcomeScreen.cloneableProjects.CloneableProjectsService.runCloneTask$lambda$1$lambda$0(CloneableProjectsService.kt:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.wm.impl.welcomeScreen.cloneableProjects.CloneableProjectsService.runCloneTask$lambda$1(CloneableProjectsService.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Version and Environment Details
Operation system: macOS 13.3.1
IDE version: IU-231.8109.175
Plugin version: 0.6.7

**Comment by Wujiaxuan007** [comment]
问题已解决，请升级至 0.7.0
