### ISSUE TITLE
Exception: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 18

### ISSUE THREAD

**Issue by zhoumq** [Wujiaxuan007/trantor-plugin-error-receiver#49]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 18
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4602)
	at java.base/java.lang.String.substring(String.java:2705)
	at io.terminus.trantor.plugin.utils.TrantorUtils.getVersionFromMavenVersion(TrantorUtils.java:328)
	at io.terminus.trantor.plugin.utils.TrantorUtils.lambda$findTrantorVersion$6(TrantorUtils.java:291)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at io.terminus.trantor.plugin.utils.TrantorUtils.findTrantorVersion(TrantorUtils.java:288)
	at io.terminus.trantor.plugin.meta.module.PluginModule.setAndCheckApiModule(PluginModule.java:107)
	at io.terminus.trantor.plugin.explorer.TModuleExplorer.lambda$findApiModule$3(TModuleExplorer.java:211)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.terminus.trantor.plugin.explorer.TModuleExplorer.findApiModule(TModuleExplorer.java:206)
	at io.terminus.trantor.plugin.explorer.TModuleExplorer.explore(TModuleExplorer.java:174)
	at io.terminus.trantor.plugin.explorer.TModuleExplorer.doExplore(TModuleExplorer.java:149)
	at io.terminus.trantor.plugin.project.manager.TProjectManager.exploreTModules(TProjectManager.java:72)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:112)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:149)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:112)
	at io.terminus.trantor.plugin.project.manager.TProjectManager.reloadTModuleList(TProjectManager.java:67)
	at io.terminus.trantor.plugin.navigator.TTreeStructure$1.run(TTreeStructure.java:101)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Version and Environment Details
Operation system: macOS 13.2.1
IDE version: IU-231.8109.175
Plugin version: 0.7.0

**Comment by Wujiaxuan007** [comment]
trantor-framework 依赖版本是多少？
