### ISSUE TITLE
Exception: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1

### ISSUE THREAD

**Issue by Wujiaxuan007** [Wujiaxuan007/trantor-plugin-error-receiver#5]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1788)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
	at java.base/java.lang.String.split(String.java:2317)
	at java.base/java.lang.String.split(String.java:2364)
	at io.terminus.trantor.plugin.loader.ViewLoader.lambda$getData$0(ViewLoader.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at io.terminus.trantor.plugin.loader.ViewLoader.getData(ViewLoader.java:62)
	at io.terminus.trantor.plugin.meta.model.PluginModelResource.<init>(PluginModelResource.java:59)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.apply(ModelResourceLoader.java:127)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.lambda$getTrantorModelList$2(ModelResourceLoader.java:85)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.getTrantorModelList(ModelResourceLoader.java:87)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.lambda$getData$0(ModelResourceLoader.java:74)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.lambda$getData$1(ModelResourceLoader.java:70)
	at java.base/java.util.Map.forEach(Map.java:661)
	at io.terminus.trantor.plugin.loader.ModelResourceLoader.getData(ModelResourceLoader.java:70)
	at io.terminus.trantor.plugin.meta.module.PluginModuleResource.<init>(PluginModuleResource.java:26)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.terminus.trantor.plugin.handle.TModuleHandle.handle(TModuleHandle.java:18)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.concurrent.ConcurrentSkipListMap$ValueSpliterator.forEachRemaining(ConcurrentSkipListMap.java:3246)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.terminus.trantor.plugin.project.manager.TProjectManager.exploreTModules(TProjectManager.java:52)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:103)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:140)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:103)
	at io.terminus.trantor.plugin.project.manager.TProjectManager.reloadTModuleList(TProjectManager.java:44)
	at io.terminus.trantor.plugin.navigator.TTreeStructure$1.run(TTreeStructure.java:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Version and Environment Details
Operation system: Windows 10 10.0
IDE version: IU-203.6682.168
Plugin version: 0.4.9
Trantor version: 0.14

**Comment by Wujiaxuan007** [comment]
0.4.10 已修复
