### ISSUE TITLE
Exception: java.lang.ClassCastException: class io.terminus.trantor.plugin.navigator.node.TViewActionNode cannot be cast to class io.terminus.trantor.plugin.navigator.node.TViewNode (io.terminus.trantor.plugin.navigator.node.TViewActionNode and io.terminus.trantor.plugin.navigator.node.TViewNode are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @6b8c1aed)

### ISSUE THREAD

**Issue by xuxiaotengxxt** [Wujiaxuan007/trantor-plugin-error-receiver#56]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.ClassCastException: class io.terminus.trantor.plugin.navigator.node.TViewActionNode cannot be cast to class io.terminus.trantor.plugin.navigator.node.TViewNode (io.terminus.trantor.plugin.navigator.node.TViewActionNode and io.terminus.trantor.plugin.navigator.node.TViewNode are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @6b8c1aed)
	at io.terminus.trantor.plugin.reference.node.TViewJsonRef.resolve(TViewJsonRef.java:26)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:177)
	at com.intellij.codeInsight.TargetEvaluatorAwareReference.getTargetElement(TargetEvaluatorAwareReference.java:75)
	at com.intellij.codeInsight.TargetEvaluatorAwareReference.resolveReference(TargetEvaluatorAwareReference.java:61)
	at com.intellij.model.psi.impl.TargetsKt.referencedSymbols(targets.kt:28)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:18)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getTargetSymbols(IdentifierHighlighterPass.java:233)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:225)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:90)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:410)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

### Version and Environment Details
Operation system: Windows 10 10.0
IDE version: IU-201.7846.76
Plugin version: 0.7.0
Trantor version: 0.13

**Comment by Wujiaxuan007** [comment]
升级到 0.8.0
