### ISSUE TITLE
Exception: java.util.MissingResourceException: Registry key ide.helptooltip.enabled is not defined

### ISSUE THREAD

**Issue by hackk7** [Wujiaxuan007/trantor-plugin-error-receiver#61]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.util.MissingResourceException: Registry key ide.helptooltip.enabled is not defined
	at com.intellij.openapi.util.registry.Registry.getBundleValue$intellij_platform_util(Registry.kt:363)
	at com.intellij.openapi.util.registry.RegistryValue.resolveRequiredValue(RegistryValue.kt:198)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.kt:49)
	at com.intellij.openapi.util.registry.Registry$Companion.is(Registry.kt:85)
	at com.intellij.openapi.util.registry.Registry.is(Registry.kt)
	at io.terminus.trantor.plugin.navigator.custom.component.toolbar.RefreshTrantorApiJarAction$2.updateToolTipText(RefreshTrantorApiJarAction.java:104)
	at com.intellij.openapi.actionSystem.impl.ActionButton.addNotify(ActionButton.java:303)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:340)
	at com.intellij.openapi.editor.toolbar.floating.AbstractFloatingToolbarComponent.addNotify(AbstractFloatingToolbarComponent.kt:70)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
	at com.intellij.ui.tabs.impl.JBTabsImpl.addImpl(JBTabsImpl.kt:2724)
	at java.desktop/java.awt.Container.add(Container.java:440)
	at com.intellij.ui.tabs.impl.JBTabsImpl.updateContainer(JBTabsImpl.kt:2635)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.kt:1510)
	at com.intellij.ui.tabs.impl.JBTabsImpl.access$executeSelectionChange(JBTabsImpl.kt:107)
	at com.intellij.ui.tabs.impl.JBTabsImpl$doSetSelected$1.run(JBTabsImpl.kt:1471)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.lambda$3$lambda$2(EditorTabbedContainer.kt:120)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:226)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer._init_$lambda$3(EditorTabbedContainer.kt:118)
	at com.intellij.ui.tabs.impl.JBTabsImpl.doSetSelected(JBTabsImpl.kt:1469)
	at com.intellij.ui.tabs.impl.JBTabsImpl.removeTab(JBTabsImpl.kt:2491)
	at com.intellij.ui.tabs.impl.JBTabsImpl.removeTab$default(JBTabsImpl.kt:2448)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$intellij_platform_ide_impl(EditorWindow.kt:680)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$intellij_platform_ide_impl$default(EditorWindow.kt:656)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile$lambda$17(FileEditorManagerImpl.kt:746)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile$intellij_platform_ide_impl(FileEditorManagerImpl.kt:745)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.kt:767)
	at com.intellij.openapi.fileEditor.impl.tabActions.CloseTab.actionPerformed(CloseTab.kt:104)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:374)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:32)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$actionProcessor$1.performAction(IdeKeyEventDispatcher.kt:499)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$8$lambda$7(IdeKeyEventDispatcher.kt:850)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:98)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$8(IdeKeyEventDispatcher.kt:850)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1173)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.kt:396)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner(IdeKeyEventDispatcher.kt:848)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doPerformActionInner(IdeKeyEventDispatcher.kt:1)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:577)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:512)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.kt:451)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.kt:444)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.kt:306)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:606)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$22(IdeEventQueue.kt:565)
	at com.intellij.openapi.applic...
```

### Version and Environment Details
Operation system: macOS 14.4
IDE version: IU-243.22562.145
Plugin version: 0.8.1

**Comment by Wujiaxuan007** [comment]
升级到 0.9.0 可解决
